### ISSUE TITLE
Android 10: online/offline problems via wifi plugin

### ISSUE THREAD

**Issue by Maho38** [sushichop/cordova-plugin-wifi-manager#19] opened 2021-04-27 14:04 UTC
### Problem
I open my app without internet connection (no wifi, no cellular connection). Then I connect via this plugin to a wifi stick with a sim card inside which is online but the wifi icon shows an "!" and I don't have internet connection.

Same error if I have a wifi connection with internet access to my home wifi, then open the app and connect via plugin to my wifi stick.

If I connect manually (without the plugin) everything works fine.

It also works fine if I am online via cellular connection on my phone, open the app and connect via plugin to the stick. But if I lose wifi connection and the phone connects automatically to cellular and/or home-wifi the app things I am offline while other apps have internet connection. If I close my app and open it again i am online.

Has anybody the same problem? Is it a bug or may I have to add/change a configuration?

**Comment by xFryx** [comment] 2021-05-06 21:31
I have the same problem...

**Comment by mohammdkhalilii** [comment] 2021-06-16 17:18
I have same problem

**Comment by yanngarras** [comment] 2021-06-18 13:13
Hi, 

IMO it is "normal" event if it is really annoying. 

You say "I don't have internet connection." but I think that none of your Smartphone application (or the system) will access to internet using this Wifi connexion but if you try to make a network request inside your application, it must succeed. 

I tried it successfully on a Xaomi Mi 9T Pro running Android 10.

Regards,

Yann

**Comment by sushichop** [comment] 2021-06-19 07:40
Thanks for reporting this.
Unfortunately I haven't touched Android recently and tested well the latest plugin version(and cordova-android).

Can you try the previous plugin version(cordova-plugin-wifimanager@0.2.1)? 
It uses obsolete API, but I think it works as a workaround probably. 

```
cordova plugin remove cordova-plugin-wifi-manager --save
cordova plugin add cordova-plugin-wifi-manager@0.2.1 --save
cordova plugin ls
cordova prepare
```

Thanks.

**Comment by sushichop** [comment] 2021-06-20 12:11
Hi all, 
the workaround is as follows.

```
cordova plugin remove cordova-plugin-wifi-manager --save
cordova plugin add cordova-plugin-wifi-manager@0.2.1 --save
cordova plugin ls
cordova prepare
cordova run android --device -- --gradleArg=-PcdvTargetSdkVersion=28 
```

This should work with cordova-plugin-wifi-manager@0.2.1.

Please note that this is a workaround with an outdated API. I'll investigate the latest cordova-pluigin-wifi-manager if I spare time. Unfortunately I don't have enough time to do it these days...

Thanks.

**Comment by Maho38** [comment] 2021-06-24 14:27
Hi @sushichop,
thank you very much for your answer. For internal tests It works but using this old api version and upload the apk to the play store is not possible because google wants Api level 29 or 30.

I will wait until you have an update.
Thank you for this great plugin!

**Comment by sushichop** [comment] 2021-07-05 10:54
I have released cordova-plugin-wifi-manager@0.4.0 which fixes a few things and has some changes. Basically, 0.3.0 works as well, but I recommend you use 0.4.0.
I have tested and checked that it works several times. The important things are as follows.

__When you use this plugin for Android 10 (API level 29) or later, you can connect to the Internet only through your own (cordova)  app. This is due to the specification of new Android API, [WifiNetworkSpecifier](https://developer.android.com/reference/android/net/wifi/WifiNetworkSpecifier).__
I added the same notice in README.md.

For example, you will see that your (cordova) app connects to the web page on the Internet by using [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) with `cordova-plugin-wifi-manager`.

Thanks.

**Comment by sushichop** [comment] 2021-07-09 13:56
Additional information.

I have actually created cordova app and confirmed that it works through WebView.
For example, the sample code for `https://httpbin.org/get`  is as follows.

```js
const httpGet = () => {
  fetch('https://httpbin.org/get')
    .then(response => response.text())
    .then(text => {
      console.log(text);
    })
    .catch(error => {
      console.log(error);
    });
};

document.addEventListener('deviceready', httpGet, false);
```

Don't forget to rewrite the part in `index.html` that starts with `<meta http-equiv="Content-Security-Policy"`.

```html
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com https://httpbin.org; style-src 'self'; media-src *; img-src 'self' data: content:;">
```

I hope this information is useful to you.

**Comment by sushichop** [comment] 2021-07-14 12:14
I'm closing this issue since it is the specification of Android API rather than an issue.
But if you still have the issue, feel free to reopen or create another issue.

Thanks.

**Closed as completed by sushichop** 2021-07-14 12:14 UTC
Labels: question

**Comment by rahulOndo** [comment] 2021-07-20 16:09
Hi @sushichop ,

Thank you for the nice plugin.
I am using it in ionic application with android platform.
I am facing the same issue as @Maho38 though i am using the latest version 0.4.1.
In my case i am connecting to the IOT bridge network using this plugin connect API. I am successfully able to connect to BRIDGE network. Since i am on BRIDGE network i am able to successfully communicate with bridge API.  After that bridge become offline so our phone automatically gets connected to the Home wifi network. Though my phone as Internet connection my app does not and as a result all API call gets failed.
When i kill  and relaunch it has network access and everything works fine.

I feel like app is caching the network configuration and though Phone is connected to different network, App is trying to use the older one which is offline now.

Please share your view.

Thanks!

**Comment by sushichop** [comment] 2021-08-07 14:44
@rahulOndo 

Thanks for sharing your information.
I'm not sure, but I think you are right probably.
I think you need to call `disconnect` method once and then use call `connect` method to connect to the SSID of home wifi network as a new access point.

Thanks.
