### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by mohammdkhalilii** [sushichop/cordova-plugin-wifi-manager#23] opened 2021-06-18 13:08 UTC
At first I must say thank you for this plugin .
I have same problem like @Maho38 , When plugin connect to Wifi network ; this seems phone did not connection with network and they couldn't even access other clients .
But when connect manually , it is totally fine.
Thank you.

**Comment by sushichop** [comment] 2021-06-19 07:40
Thanks for reporting this.
Unfortunately I haven't touched Android recently and tested well the latest plugin version(and cordova-android).

Can you try the previous plugin version(cordova-plugin-wifimanager@0.2.1)? 
It uses obsolete API, but I think it works as a workaround probably. 

```
cordova plugin remove cordova-plugin-wifi-manager --save
cordova plugin add cordova-plugin-wifi-manager@0.2.1 --save
cordova plugin ls
cordova prepare
```

Thanks.

**Comment by mohammdkhalilii** [comment] 2021-06-19 16:57
Thank for your quick reply.
I have tested version 0.21, it's totally fine with android 9 and earlier; but with android 10 and later it returns error code 1001 or  "addNetwork failed." 
Could you please tell me how to fix this issue?
Regard.

**Comment by sushichop** [comment] 2021-06-20 12:06
It was about a year ago that I originally tested it using my Android 10 device. It seems that the version of cordova-android has been upgraded now.
After uninstalling the cordova app, please run the following as an additional workaround to re-install the cordova app.

```
cordova run android --device -- --gradleArg=-PcdvTargetSdkVersion=28 
```

This should work with cordova-plugin-wifi-manager@0.2.1.

Please note that this is a workaround with an outdated API. I'll investigate the latest cordova-pluigin-wifi-manager if I spare time. Unfortunately I don't have enough time to do it these days.

Thanks.

**Comment by sushichop** [comment] 2021-07-05 10:54
I have released cordova-plugin-wifi-manager@0.4.0 which fixes a few things and has some changes. Basically, 0.3.0 works as well, but I recommend you use 0.4.0.
I have tested and checked that it works several times. The important things are as follows.

__When you use this plugin for Android 10 (API level 29) or later, you can connect to the Internet only through your own (cordova) native app. This is due to the specification of new Android API, [WifiNetworkSpecifier](https://developer.android.com/reference/android/net/wifi/WifiNetworkSpecifier).__
I added the same notice in README.md.

For example, you will see that your (cordova) app connects to the web page on the Internet by using [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) with `cordova-plugin-wifi-manager`.

Thanks.

**Comment by Maho38** [comment] 2021-07-06 08:10
Thanks you very much for that update! You are right, connecting with cordova-plugin-wifi-manager and using cordova-plugin-inappbrowser works with Android 10 or later.
You wrote "...you can connect to the Internet only through your own (cordova) app.". Can you give me a hint how to do this using an iframe or make an ajax call from my cordova app to a webserver, please?

Thanks!

**Comment by sushichop** [comment] 2021-07-06 13:17
Oops! 
You can access it using cordova-plugin-inappbrowser to be precise. 

> Can you give me a hint how to do this using an iframe or make an ajax call

~~Unfortunately, I don't know of a way to use the above. But, probably I think you can also access through your ~~cordova~~ native apps using Java or Kotlin probably. I updated the above comment.~~

**Comment by sushichop** [comment] 2021-07-09 13:54
@Maho38 
I updated README again. 

> Can you give me a hint how to do this using an iframe or make an ajax call

Good news. I have actually created cordova app and confirmed that it works through WebView. 
I recommend you use fetch rather than ajax.
For example, the sample code for `https://httpbin.org/get`  is as follows.

```js
const httpGet = () => {
  fetch('https://httpbin.org/get')
    .then(response => response.text())
    .then(text => {
      console.log(text);
    })
    .catch(error => {
      console.log(error);
    });
};

document.addEventListener('deviceready', httpGet, false);
```

Don't forget to rewrite the part in `index.html` that starts with `<meta http-equiv="Content-Security-Policy"`.

```html
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com https://httpbin.org; style-src 'self'; media-src *; img-src 'self' data: content:;">
```

I hope this information is useful to you.

**Comment by Maho38** [comment] 2021-07-13 09:33
Thank you very much! With fetch instead of ajax it seems to work!

**Comment by sushichop** [comment] 2021-07-14 12:14
I'm closing this issue since it is the specification of Android API rather than an issue.
But if you still have the issue, feel free to reopen or create another issue.

Thanks.

**Closed as completed by sushichop** 2021-07-14 12:14 UTC
Labels: question
